### ISSUE TITLE
hook.sub is undefined in relay-devtools-core

### ISSUE THREAD

**Issue by ghost** [th3rdwave/flipper-plugin-relay-devtools#4]
Dear @janicduplessis,

thanks for providing this package and https://github.com/janicduplessis/relay-devtools. As the latter is forked I can't create an issue there so I did it here.

Sadly for some reason I'm getting the error `[TypeError: hook.sub is not a function. (In 'hook.sub('environment.event', function (data) {
            agent.onEnvironmentEvent(data);
          })', 'hook.sub' is undefined)]`. I've inspected `window.__RELAY_DEVTOOLS_HOOK__` and seen that `on`, `sub` and `emit` are completely missing.

I'd highly appreciate it if you could either provide me with the untranspiled source of `relay-devtools-core` for me to debug or provide me with some form of other assistance.

Thanks in advance!

Best regards
Marces Engel

**Comment by janicduplessis** [comment]
I can try to update the fork to the latest version and see if it fixes that.

**Comment by janicduplessis** [comment]
I tested and everything now works with relay@11. Make sure to check the release notes here https://github.com/th3rdwave/flipper-plugin-relay-devtools/releases/tag/v1.0.0 on how to update. Also verify that the plugin is version 1.0.2 in Flipper.

**Comment by ghost** [comment]
Thank you very much 🎉  I'll test it later today and give you a heads up, thanks again :)

**Comment by ghost** [comment]
Hey @janicduplessis, sorry for the late response. I'm still having issues using the plugin as it complains "The DevTools didn't connect yet. Please verify your React Native app is in development mode, **and that no other instance of the React DevTools are attached to the app already.**" However it seems impossible for me to prevent this from happening because Flipper itself also launches an instance of the React DevTools - how do you circumvent this?

Thanks in advance for your assistance.
