### ISSUE TITLE
Flipper plugin definition is broken

### ISSUE THREAD

**Issue by ghost** [th3rdwave/flipper-plugin-relay-devtools#6]
Hi,

it seems like flipper changed the way plugins are defined. I've created a PR containing the required changes, some dependency version bumps and exposed a transpiled version of `client.tsx` as `main` - see #5.

I'd much appreciate if it was merged and you'd also update it on npm and the flipper registry.

Thanks in advance.

Best regards
Marces Engel

**Comment by janicduplessis** [comment]
Thanks for the PR, will work on a new release later today
